### PR TITLE
Added comments

### PR DESCRIPTION
**Pull request by AC159**
- Added comments

### CODE REVIEW

**Comment by kwl2000** [comment]
What's wrong with travis CI?

**Comment by AC159** [comment]
> What's wrong with travis CI?

Tests are not implemented properly which is why it is failing...Ryan should be working on it.

**Comment by kwl2000** [comment]
Ah, I see, gotcha. Thanks for clarifying.

**Comment by NicholasYip** [comment]
the comments really help me understand your code more!

**Pull request merged**
